### ISSUE TITLE
BUG FIX ASAP.

### ISSUE THREAD

**Issue by MCEpicShasta** [MCEpicNation/GalaxyNetworkMAB#1]
**Describe the bug**
omfg. you know exactly what it is

**To Reproduce**

**Expected behavior**

**Screenshots**
http://prntscr.com/n4dhpi
**Additional context**

**Comment by MCEpicShasta** [comment]
ur gay

**Comment by TigritoPlaysMC** [comment]
nou

**Comment by MCEpicNation** [comment]
Issue Resolved.

**Comment by MCEpicShasta** [comment]
no

**Comment by MCEpicShasta** [comment]
d
